apiVersion: v1
kind: Service
metadata:
  name: {{include "data-health-check.fullname" .}}
  labels: {{- include "data-health-check.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: 80
      targetPort: {{.Values.service.targetPort}}
      protocol: TCP
      name: http
    - port: 443
      targetPort: {{.Values.service.targetPort}}
      protocol: TCP
      name: https
  selector: {{- include "data-health-check.selectorLabels" . | nindent 4}}
